#!/bin/bash

#
# This file belongs to the SRxCryptoAPI testbed. The certificates/keys 
# generated here are for test purpose only and might not follow the BGPSEc 
# certificate structure.
# They are not intended to be used elsewhere than the test bed.
# 

EXT_DER="der"
EXT_PEM="pem"
EXT_CERT="cert"
SKI_LIST="ski-list.txt"

QSRX_VIEW=qsrx-view-subject
QSRX_MAKE_KEY=qsrx-make-key
QSRX_MAKE_CERT=qsrx-make-cert

WITH_PEM=0

if [ "$1" != "" ] ; then
  if [ "$1" == "--with-pem" ] ; then
    WITH_PEM=1
    shift;
  fi
fi

if [ "$1" == "" ] ; then
  echo "$0 [--with-pem] <cert-name> [<repository path>]"
  exit 1
fi

REPO_ROOT="/var/lib/bgpsec-keys"
if [ "$2" != "" ] ; then
  REPO_ROOT=$2
fi
BIRD_REPO="$REPO_ROOT/bird"
if [ ! -e $BIRD_REPO ] ; then
  echo "Create BIRT key repo at '$BIRD_REPO'"
  mkdir -p $BIRD_REPO
  if [ $? -eq 1 ] ; then
    exit 3
  fi
fi

ALL_GOOD=0

if [ -e "$1.$EXT_CERT" ] ; then
  if [ -e "$1.$EXT_DER" ] ; then
    if [ $WITH_PEM -eq 1 ] ; then
      if [ -e "$1.$EXT_PEM" ] ; then
        ALL_GOOD=1
      fi
    else
      ALL_GOOD=1
    fi

    if [ $ALL_GOOD -eq 1 ] ; then
      SUBJECT=$($QSRX_VIEW $1)
      DIR1=$(echo $SUBJECT | sed -e "s/\([0-9a-zA-Z][0-9a-zA-Z]\).*/\1/g")
      DIR2=$(echo $SUBJECT | sed -e "s/\([0-9a-zA-Z][0-9a-zA-Z]\)\([0-9a-zA-Z][0-9a-zA-Z][0-9a-zA-Z][0-9a-zA-Z]\).*/\2/g")
      FILE=$(echo $SUBJECT | sed -e "s/\([0-9a-zA-Z][0-9a-zA-Z][0-9a-zA-Z][0-9a-zA-Z][0-9a-zA-Z][0-9a-zA-Z]\)\(.*\)/\2/g")      

      BIRD_FILE_PUB=$1.$SUBJECT.0.key 
      BIRD_FILE_PRIV=$1.$SUBJECT.key

      REPOSITORY=$REPO_ROOT/$DIR1/$DIR2
      KEYVOLT=$REPO_ROOT/$DIR1/$DIR2
      #KEYVOLT=$REPO_ROOT/keys

      DO_REGISTER=0

      echo "Publish cert and key into $REPOSITORY and $BIRD_REPO"
      # Check if public key exists already!!
      if [ -e $REPOSITORY/$FILE.$EXT_CERT ] ; then
        echo " * public key $REPOSITORY/$FILE.$EXT_CERT already installed!!"
      else
        mkdir -p $REPOSITORY
        cp $1.$EXT_CERT $REPOSITORY/$FILE.$EXT_CERT
        cp $1.$EXT_CERT $BIRD_REPO/$BIRD_FILE_PUB
        DO_REGISTER=1
      fi

      if [ -e $KEYVOLT/$FILE.$EXT_DER ] ; then
        echo " * private key $REPOSITORY/$FILE.$EXT_DER already installed!!"
      else
        mkdir -p $KEYVOLT
        cp $1.$EXT_DER  $KEYVOLT/$FILE.$EXT_DER
        cp $1.$EXT_DER  $BIRD_REPO/$BIRD_FILE_PRIV
        DO_REGISTER=1
      fi

      if [ $WITH_PEM -eq 1 ] ; then
        if [ -e $KEYVOLT/$FILE.$EXT_PEM ] ; then
          echo " * private key $REPOSITORY/$FILE.$EXT_PEM already installed!!"
        else
          cp $1.$EXT_PEM  $KEYVOLT/$FILE.$EXT_PEM
          DO_REGISTER=1
        fi
      fi

      if [ $DO_REGISTER -eq 1 ] ; then
        echo "Register $1-SKI=$SUBJECT"
        echo "$1-SKI: $SUBJECT" >> $REPO_ROOT/$SKI_LIST
      else
        echo "$1-SKI=$SUBJECT already registered"
      fi
    else
      echo "Key $1.$EXT_PEM not found! Please generate a key and certificate first using:"
      echo "- Generate a key using '$QSRX_MAKE_KEY $1'"
      echo "- Generate a certificate '$QSRX_MAKE_CERT $1'"
    fi
  else
    echo "Key $1.$EXT_DER not found! Please generate a key and certificate first using:"
    echo "- Generate a key using '$QSRX_MAKE_KEY $1'"
    echo "- Generate a certificate '$QSRX_MAKE_CERT $1'"
  fi
else
  echo "Certificate $1.$EXT_CERT not found! Please generate a certificate first using:"
  echo "- Generate a certificate '$QSRX_MAKE_CERT $1'"
fi
