/**
 * This software was developed at the National Institute of Standards and
 * Technology by employees of the Federal Government in the course of
 * their official duties. Pursuant to title 17 Section 105 of the United
 * States Code this software is not subject to copyright protection and
 * is in the public domain.
 *
 * NIST assumes no responsibility whatsoever for its use by other parties,
 * and makes no guarantees, expressed or implied, about its quality,
 * reliability, or any other characteristic.
 *
 * We would appreciate acknowledgment if the software is used.
 *
 * NIST ALLOWS FREE USE OF THIS SOFTWARE IN ITS "AS IS" CONDITION AND
 * DISCLAIM ANY LIABILITY OF ANY KIND FOR ANY DAMAGES WHATSOEVER RESULTING
 * FROM THE USE OF THIS SOFTWARE.
 *
 *
 * This software might use libraries that are under GNU public license or
 * other licenses. Please refer to the licenses of all libraries required
 * by this software.
 *
 * cfgFile allows to generate a fully functional sample configuration file
 * for BGPSEC-IO
 * 
 * @version 0.2.0.2
 * 
 * Changelog:
 * -----------------------------------------------------------------------------
 *  0.2.0.2 - 2016/06/29 - oborchert
 *            * Fixed usage of invalid algorithm ID in auto generation. (BZ997)
 *            * Added check if file exists already (BZ996)
 *          - 2016/06/28 - oborchert
 *            * Removed the generation of useMPNLRI  
 *  0.2.0.0 - 2016/05/13 - oborchert
 *            * Added maximum number of updates to be processed '-M'.
 *          - 2016/05/11 - oborchert
 *            * Removed duplicate syntax (copy past error)
 *            * Added missing semicolon in generated configuration file.
 *          - 2016/05/10 - oborchert
 *            * BZ955: Added generation of "asn" and "capi_cfg" to configuration
 *              generation.
 *          - 2016/05/06 - oborchert
 *            * Added generation of "capi_cfg" parameter.
 *  0.1.1.0 - 2016/05/03 - oborchert
 *            * Added appendOut.
 *          - 2016/04/29 - oborchert
 *            * Modified signature of function generateFile by removing the 
 *              program Parameters. The generated file is a sample configuration
 *              containing all possible settings.
 *            * Updated to reflect latest configuration settings.
 *  0.1.0.0 - 2015/11/29 - oborchert
 *            * Created File.
 */

#include <stdio.h>
#include <stdbool.h>
#include <stddef.h>
#include <string.h>
#include <unistd.h>
#include "configuration.h"
#include "antd-util/prefix.h"

/**
 * Generate an example configuration file..
 * 
 * @param fName The name of the configuration file.
 * 
 * @return true if the file could be generated, false if no name was given or the
 *              file already exists.
 */
bool generateFile(char* fName)
{
  if (fName == NULL)
  {
    return false;
  }
  
  if ( access(fName, F_OK) != -1 )
  {
    // File exists
    return false;
  }
  
  FILE* file = fopen(fName, "w");
    
  if (file)
  {
    fprintf (file, "#BGPSEC-IO Configuration file. Auto generated by %s %s\n\n", 
                  PRG_NAME, PRG_VERSION);
    fprintf (file, "%s    = \"%s\";\n", P_CFG_SKI_FILE, DEF_SKIFILE);
    fprintf (file, "%s = \"%s\";\n\n", P_CFG_SKI_LOC, DEF_KEYLOCATION);

    fprintf (file, "%s = false;\n\n", P_CFG_PL_ECKEY);
    
    fprintf (file, "# Choose from the following types \"%s\", \"%s\", \"%s\", "
                   "and \"%s\"\n",
                   P_TYPE_BGP, P_TYPE_CAPI, P_TYPE_GENB, P_TYPE_GENC);
    fprintf (file, "%s = \"%s\";\n", P_CFG_TYPE, P_TYPE_BGP);
    // Max number up updates
    fprintf (file, "# Maximum combined number of updates to process. Script 0 "
                   "for MAX INT\n");
    fprintf (file, "%s = 0;\n\n", P_CFG_MAX_UPD);
    
    // infile
    fprintf (file, "# %s = \"<binary input file>\";\n", P_CFG_BINFILE);
    
    // Outfile
    fprintf (file, "# %s = \"<binary output file>\";\n", P_CFG_OUTFILE);
    
    // appendOut
    fprintf (file, "# Append data to the out file.\n");  
    fprintf (file, "%s = \"false\";\n\n", P_CFG_APPEND_OUT);
    
    // capi_cfg
    fprintf (file, "# Allow to specify a config file for srx-crypto-api, If "
                   "this is not specified,\n");
    fprintf (file, "# the default srx-crypto-api configuration (determined by "
                   "the api) will be used.\n");
    fprintf (file, "#%s = \"<configuration file>\";\n\n", P_CFG_CAPI_CFG);
       
    // Create the session information
    fprintf (file, "# Multiple sessions possible (at a later time)\n");
    fprintf (file, "session = (\n");
    fprintf (file, "  {\n");
    fprintf (file, "    %s        = 64;\n", P_CFG_MY_ASN);
    fprintf (file, "    %s  = \"10.0.1.64\";\n", P_CFG_BGP_IDENT);
    fprintf (file, "    %s = 180;\n\n", P_CFG_HOLD_TIME);

    fprintf (file, "    %s   = 32;\n", P_CFG_PEER_AS);
    fprintf (file, "    %s    = \"10.0.1.32\";\n", P_CFG_PEER_IP);
    fprintf (file, "    %s  = 179;\n\n", P_CFG_PEER_PORT);

    fprintf (file, "    # Run forever or until the peer shuts down.\n");
    fprintf (file, "    %s = 0;\n\n", P_CFG_DISCONNECT_TIME);

    fprintf (file, "    # Updates for this session only\n");
    fprintf (file, "    %s = (  \"%s\"\n", P_CFG_UPD_PARAM, 
                                                    "10.0.0.0/24");
    fprintf (file, "              , \"%s, %s\"\n", "10.0.1.0/24", "10 20p3 30");
    fprintf (file, "              , \"%s, %s\"\n", "10.0.2.0/24", "10 20 40 50");
    fprintf (file, "              , \"%s, %s\"\n", "10.0.3.0/24", "10 20 60 70");
    fprintf (file, "             );\n\n");

// Removed this parameter from being added in default cofiguration. It will 
// be completely removed in future revisions and was only needed during the 
// draft13 -> draft15 merger.  
//    fprintf (file, "    #%s = true;\n\n", P_CFG_MPNLRI);
        
    fprintf (file, "    %s = %u;\n\n", P_CFG_ALGO_ID, P_CFG_ALGO_ID_DEF_VAL);
    
    fprintf (file, "    #The following settings are possible (%s| %s| %s)\n",
             P_TYPE_NSM_DROP, P_TYPE_NSM_FAKE, P_TYPE_NSM_BGP4);
    fprintf (file, "    %s = \"%s\";\n", P_CFG_NULL_SIGNATURE_MODE, 
                                        P_TYPE_NSM_FAKE);

    char* fakeTab = "                          \0";
    char* fakeSig = "BAD0BAD0BAD0BAD\0";
    fprintf (file, "    %s      = \"0%s\" \"1%s\"\n", P_CFG_FAKE_SIGNATURE, 
             fakeSig, fakeSig);
      fprintf (file, "%s\"0%s\" \"1%s\"\n", fakeTab, fakeSig, fakeSig);
      fprintf (file, "%s\"2%s\" \"3%s\"\n", fakeTab, fakeSig, fakeSig);
      fprintf (file, "%s\"4%s\" \"5%s\"\n", fakeTab, fakeSig, fakeSig);
      fprintf (file, "%s\"6%s\" \"7%s\"\n", fakeTab, fakeSig, fakeSig);
      fprintf (file, "%s\"8BAD0BAD0BAD\";\n", fakeTab);
    fprintf (file, "    %s            = \"1122334455667788\" "
                   "\"9900AABBCCDDEEFF\"\n", P_CFG_FAKE_SKI);
      fprintf (file, "%s\"11223344\";\n\n", fakeTab);
    
    // @TODO: This MUST be modified to each message type once it is 
    //        supported.
    fprintf (file, "    # Do some debug printout.\n");
    fprintf (file, "    # For BGP Mode.\n");    
    fprintf (file, "    %s    = false;\n", P_CFG_PRINT_ON_SEND);
    fprintf (file, "    %s = false;\n", P_CFG_PRINT_ON_RECEIVE);
    fprintf (file, "    %s  = false;\n\n", P_CFG_PRINT_POLL_LOOP);    
    fprintf (file, "    # For CAPI Mode.\n");    
    fprintf (file, "    %s = false;\n\n", P_CFG_PRINT_CAPI_ON_INVALID);    
    
    fprintf (file, "  }\n");

    fprintf (file, "# Currently multi sessions are not supported, that is\n");
    fprintf (file, "# the reason the following section is commented out!\n");
    fprintf (file, "#  ,{\n");
    fprintf (file, "      # Here script another session\n");    
    fprintf (file, "#  }\n\n");
    
    fprintf (file, ");\n\n");

    fprintf (file, "# global updates for all sessions\n");
    fprintf (file, "%s = ( \n", P_CFG_UPD_PARAM);
    fprintf (file, "         );\n");
    fclose(file);
  }
  
  return true;
}